version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain dependencies for maven
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"